FROM python:3.9-slim

WORKDIR /app

COPY ../backend-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../backend-service/backend_service.py .

EXPOSE 5000

CMD ["python", "backend_service.py"]