FROM python:3.9-slim

WORKDIR /app

COPY client-service/requirements-baseline.txt .
RUN pip install --no-cache-dir -r requirements-baseline.txt

COPY client-service/client_baseline.py .

CMD ["python", "client_baseline.py"]