FROM python:3.9-slim

WORKDIR /app

COPY client-service/requirements-resilient.txt .
RUN pip install --no-cache-dir -r requirements-resilient.txt

COPY client-service/client_resilient.py .

CMD ["python", "client_resilient.py"]